//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jellyfin.Plugin.Crunchyroll.Tests.Integration.WaybackMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jellyfin.Plugin.Crunchyroll.Tests1.Integration.WaybackMachine.Properties.Reso" +
                            "urces", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to �PNG
        ///
        ///
        ///IHDR��=vԂ	pHYs�� IDATx�\�wx���&lt;lJ	͸���{������{�l���{7�����
        ///�Un���BBBH $��!�M�]s�g����]I�,��3s��;cѷ����`9K�҇���P�������z8&gt;G����D�������6���#&apos;d#r��#/l
        ///·�(b�&quot;��8j;�Q;`��	c�.�bv���ؽ���5V=/�C�b;R�ؑ�����H�_��yH^X����,0�c�B2�ؐ�Y�l�=�(�^����h�:����h�z
        ///Y�ђ}�9&apos;�*��Жs
        ///�����&apos;�ut忁��3r��Aw��)����P��ѫa��G�g)
        ///=�(�r�ȫ�^.�=�X����{9a�)�ѷ��f�E�De�\a�ѐ�}���՟Go�9���c��&quot;M�0d����2�M���x|n��a�U���b����0b��Q�u���c�zc6uV[o`�z˳��&amp;j*#��l�ݷv�*��*a���ͷV�rX|J`�-�կv�r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvatarImageYuzu {
            get {
                return ResourceManager.GetString("AvatarImageYuzu", resourceCulture);
            }
        }
    }
}
